### PR TITLE
feat: start using docker entrypoint script

### PR DESCRIPTION
**Pull request by KarstenSiemer**
### Description
- Relevant Issues :

When I tried to use this image in one of our Jenkins pipelines it failed because our pipeline (for whatever reason) tries to issue a command for a container before running it to check if the images were built according to the requirements by the official docker images. Well, this failed, hence this PR.

- What Changed and Why? :

ENTRYPOINT should execute the command passed as docker run argument as required by official docker images (see https://github.com/docker-library/official-images#consistency for entrypoint consistency requirements).

- Type of change :
  - [ ] New feature
  - [ ] Bug fix for existing feature
  - [X] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [ ] Addition or Improvement of documentation

- Other:
  - [ ] Add unit tests
  - [ ] Add documentation

Also wanted to add a thank you, for all the work that has gone into this very cool tool.

### CODE REVIEW

**Comment by KarstenSiemer** [comment]
Having a second thought about this. The entry point script should be accessible without knowing the working directory beforehand.
Either by having it copied to root directory or putting into path.
I'd go with copying to /.
Negative is that we'd populate the entrypoint script 2 times.
Either way I think /rep should be part of path

**Comment by AgarFu** [comment]
As you may notice there has been a lot of changes merged in the project during the last 24 hours, none of them are conflicting with yours but keep in mind the new behavior change with regards to the way the prs are created.

**Comment by KarstenSiemer** [comment]
not sure what I did wrong when I rebased this pr. Why is the git diff showing changes that are already in the master?
My git log looks correct.

**Comment by AgarFu** [comment]
Do you mind if I close it, so you can open a new one with only your changes?

Thx!

**Pull request closed without merging**
